[![Abrir no Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Jonathan-Gil-Muller/Analise-Visualizacao-Dados_-PPGCA-/blob/main/AVD_PPGCA_2026.ipynb)

# **Análise e Visualização de dados**

Programa de Pós-Graduação em Ciências Ambientais - PPGCA

*Prof. Jonathan Gil Müller - jgmuller@furb.br*

# **Aula 01 (09/10): Introdução ao uso da linguagem Python**

*   Função de imprimir
*   Variáveis
* Operadores matemáticos
* Arredondamento
* Interação com o Python
* Listas
* Dicionários e Dataframes
* Bibliotecas
* Carregar dados externos

## Imprimir, variáveis, arredondamento

In [ ]:
# A função print é utilizada para imprimir alguma informação na tela
print('Bom dia!')

Bom dia!

In [ ]:
print(2+3)

5

In [ ]:
# Variáveis
ValorInteiro = 5         # int
b            = 2.4 * 8   # float
texto        = "Olá"     # texto

# Imprimir na tela
print(f"{texto}. O valor da variável b é: {b}")

Olá. O valor da variável b é: 19.2

In [ ]:
# 1. Coleta de Dados
nome = 'Jonathan'
disc = 'AVD'
n1 = 7.5
n2 = 5.2
n3 = 2.5

# 2. Processamento dos Dados
media = round((n1 + n2 + n3) / 3, 1)

# 3. Imprimir os resultados
print(f'A média final do {nome} em {disc} é {media}')

A média final do Jonathan em AVD é 5.1

## Interação com Python - input

In [ ]:
# Interagindo para fornecer os dados
nota1 = float(input('Qual a sua Nota 1?'))
nota2 = float(input('Qual a sua Nota 2?'))
nota3 = float(input('Qual a sua Nota 3?'))

media = (nota1 + nota2 + nota3) / 3

print(media)

Qual a sua Nota 1?6
Qual a sua Nota 2?7
Qual a sua Nota 3?8
7.0

In [ ]:
# Imprimindo o tipo de objeto da variável
print(type(nota1))

<class 'float'>

## Listas

In [ ]:
# usar [ ] para definir uma lista
lista_notas = [6.0, 7.0, 8.0]

# A função 'sum' soma todos os valores da lista
# A função 'len' retorna o total de elementos da lista
media = sum(lista_notas) / len(lista_notas)

print(media)

7.0

In [ ]:
print(type(lista_notas))

<class 'list'>

## Dicionários, dataframes e bibliotecas

In [ ]:
# Usar { } para definir um dicionário
# {'nome 01': valor 01, 'nome 02': valor 02, ...}
dicionario = {
    'nomes':['nomeA', 'nomeB', 'nomeC'],
    'nota1':[5.0, 7.0, 8.0],
    'nota2':[5.0, 5.6, 9.8],
    'nota3':[7.0, 4.6, 7.8]
}

print(dicionario)

{'nomes': ['nomeA', 'nomeB', 'nomeC'], 'nota1': [5.0, 7.0, 8.0], 'nota2': [5.0, 5.6, 9.8], 'nota3': [7.0, 4.6, 7.8]}

In [ ]:
# Uma biblioteca é como uma 'caixa de ferramentas' com várias funções já programadas
# 'pandas' é o nome da biblioteca e 'pd' é o apelido.
# Pandas é uma biblioteca com funções para manipulação de tabelas
import pandas as pd

df = pd.DataFrame(dicionario)

df.head()

   nomes  nota1  nota2  nota3
0  nomeA    5.0    5.0    7.0
1  nomeB    7.0    5.6    4.6
2  nomeC    8.0    9.8    7.8

In [ ]:
# Numpy é uma biblioteca para cálculos matemáticos
import numpy as np

media_n1 = np.mean(df['nota1'])

print(media_n1)

6.666666666666667

In [ ]:
# Criar uma nova coluna com a média dos alunos

df['Média'] = ((df['nota1'] + df['nota2'] + df['nota3']) / 3).round(1)

df.head()

   nomes  nota1  nota2  nota3  Média
0  nomeA    5.0    5.0    7.0    5.7
1  nomeB    7.0    5.6    4.6    5.7
2  nomeC    8.0    9.8    7.8    8.5

## Importar uma tabela externa de dados para o ambiente Colab

In [ ]:
dados = pd.read_excel('[Estatistica-BCD]_DadosQuestionario_20262.xlsx')

dados.describe()

,ID,Você já morou em quantas cidades?,Como você avalia seu conhecimento em Matemática?,Data de nascimento:,Como você avalia seu cuidado com sua alimentação?,Quantos livros você leu no último ano?,Quantos idiomas você sabe?
count,80.0000,80.000000,80.000000,80,80.000000,80.000000,80.000000
mean,40.5000,1.725000,6.662500,2004-08-13 08:06:00,6.225000,3.462500,1.987500
min,1.0000,0.000000,2.000000,1975-03-18 00:00:00,0.000000,0.000000,0.000000
25%,20.7500,1.000000,6.000000,2003-02-24 18:00:00,5.000000,1.000000,1.000000
50%,40.5000,1.000000,7.000000,2006-07-02 12:00:00,6.500000,2.000000,2.000000
75%,60.2500,2.000000,8.000000,2007-12-01 06:00:00,8.000000,4.000000,2.000000
max,80.0000,9.000000,10.000000,2026-12-16 00:00:00,10.000000,35.000000,15.000000
std,23.2379,1.475324,1.492121,NaN,2.210304,5.641043,1.641964

In [ ]:
media = np.mean(dados['Como você avalia seu conhecimento em Matemática?'])

print(media)

6.6625

In [ ]:
# EXERCÍCIO

#Dados
venda = 1.7
margem = 35

#Processamento
custo = (venda * 100) / (100 + margem)

#Resultado
print(custo)

1.2592592592592593

# **Aula 02 (16/10): Organização, estruturação, tratamento e qualidade de dados**

## **SLIDE 02: organização e estruturação de dados**

### Atividade 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 1. Carragar DataFrame
dados = {
    'ID Vendedor': [101, 102, 101, 103, 104],
    'Região': ['Sul', 'NORTE', 'Sul', 'sul', 'Leste'],
    'FATURAMENTO': [5000, 3000, 5000, np.nan, 4500],
    'Email': [
        'ana@furb.br',
        'bruno@furb.br',
        'ana@furb.br',
        'carla@furb.br',
        'joao@furb.br',
    ]
}

df = pd.DataFrame(dados)
print(df)

# Carregar diretamento do Excel
#df = pd.read_excel("file_name")

   ID Vendedor Região  FATURAMENTO          Email
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
2          101    Sul       5000.0    ana@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 2. Renomeação das colunas

df1 = df.rename(columns={
    'ID Vendedor': 'ID_VENDEDOR',
    'Região': 'REGIAO',
    'Email': 'EMAIL'
})

print(df1)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
2          101    Sul       5000.0    ana@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 3. Eliminação de duplicatas

df2 = df1.drop_duplicates(subset=['EMAIL'])
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 4. Tratamento de Dados Ausentes

df2['FATURAMENTO'] = df2['FATURAMENTO'].fillna(0)

print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
3          103    sul          0.0  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

/tmp/ipykernel_1247/3316359745.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['FATURAMENTO'] = df2['FATURAMENTO'].fillna(0)

In [ ]:
# 5. Criação de uma coluna calculada

df2['FATURAMENTO-ANUAL'] = df2['FATURAMENTO']*12
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

/tmp/ipykernel_1247/1095340127.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['FATURAMENTO-ANUAL'] = df2['FATURAMENTO']*12

In [ ]:
# 5. Criação de uma nova coluna com lista de valores

df2['PERC-COMISSAO'] = [10, 20, 15, 10]
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

   PERC-COMISSAO
0             10
1             20
3             15
4             10

/tmp/ipykernel_1247/2344827271.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['PERC-COMISSAO'] = [10, 20, 15, 10]

In [ ]:
# 5. Criação de uma nova coluna operando com mais de uma coluna

df2['LUCRO'] = df2['FATURAMENTO-ANUAL'] - df2['PERC-COMISSAO']/100 * df2['FATURAMENTO-ANUAL']
print(df2)

In [ ]:
# 6. Padronização e ordenação

df2['REGIAO'] = df2['REGIAO'].str.lower()
df2 = df2.sort_values(by='FATURAMENTO', ascending=False)

print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    sul       5000.0    ana@furb.br            60000.0
4          104  leste       4500.0   joao@furb.br            54000.0
1          102  norte       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0

   PERC-COMISSAO
0             10
4             10
1             20
3             15

/tmp/ipykernel_1247/385625080.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['REGIAO'] = df2['REGIAO'].str.lower()

In [ ]:
# 7. Exportação Final

df2.to_excel('dados_processados.xlsx', index=False)
df2.to_csv('dados_processados.csv', index=False)

### Atividade 2

In [ ]:
import pandas as pd

In [ ]:
# 1. Criando as tabelas

df_alunos = pd.DataFrame({
    'id_aluno': [1, 2, 3, 4, 5],
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana', 'Eduardo']
})

df_novos_alunos = pd.DataFrame({
    'id_aluno': [6, 7, 8, 9, 10],
    'Nome': ['Fernanda', 'Gabriel', 'Helena', 'Igor', 'Julia']
})

df_notas = pd.DataFrame({
    'id_aluno': [1, 2, 4, 6, 8, 11],
    'Nota_Final': [8.5, 7.0, 9.2, 6.5, 8.0, 10.0]
})

print('df_alunos')
print(df_alunos,'\n')
print('df_novos_alunos')
print(df_novos_alunos,'\n')
print('df_notas')
print(df_notas)

df_alunos
   id_aluno     Nome
0         1      Ana
1         2    Bruno
2         3   Carlos
3         4    Diana
4         5  Eduardo

df_novos_alunos
   id_aluno      Nome
0         6  Fernanda
1         7   Gabriel
2         8    Helena
3         9      Igor
4        10     Julia

df_notas
   id_aluno  Nota_Final
0         1         8.5
1         2         7.0
2         4         9.2
3         6         6.5
4         8         8.0
5        11        10.0

In [ ]:
# 2. Empilhar as listas de alunos

df_alunos_completo = pd.concat([df_alunos, df_novos_alunos], ignore_index=True)

print('df_alunos_completo')
print(df_alunos_completo)

df_alunos_completo
   id_aluno      Nome
0         1       Ana
1         2     Bruno
2         3    Carlos
3         4     Diana
4         5   Eduardo
5         6  Fernanda
6         7   Gabriel
7         8    Helena
8         9      Igor
9        10     Julia

In [ ]:
# 3. Cruzamento da lista de alunos com o registro das notas

df_relatorio_final = pd.merge(df_alunos_completo,
                              df_notas,
                              on='id_aluno',
                              how='outer')

print("df_relatorio_final")
print(df_relatorio_final)

df_relatorio_final
    id_aluno      Nome  Nota_Final
0          1       Ana         8.5
1          2     Bruno         7.0
2          3    Carlos         NaN
3          4     Diana         9.2
4          5   Eduardo         NaN
5          6  Fernanda         6.5
6          7   Gabriel         NaN
7          8    Helena         8.0
8          9      Igor         NaN
9         10     Julia         NaN
10        11       NaN        10.0

Utilizar o 'df-Relatorio_final' para realizar alguns filtros

In [ ]:
# 1. Filtrar alunos que estão sem nota (NaN)

sem_nota = df_relatorio_final.loc[df_relatorio_final['Nota_Final'].isna()]

print(sem_nota)

   id_aluno     Nome  Nota_Final
2         3   Carlos         NaN
4         5  Eduardo         NaN
6         7  Gabriel         NaN
8         9     Igor         NaN
9        10    Julia         NaN

In [ ]:
# 2. Filtrar os 3 primeiros registros (posições 0, 1 e 2)
tres_primeiros = df_relatorio_final.iloc[0:3]

print(tres_primeiros)

   id_aluno    Nome  Nota_Final
0         1     Ana         8.5
1         2   Bruno         7.0
2         3  Carlos         NaN

In [ ]:
# 3. Filtros por linha e coluna

filtro = df_relatorio_final.iloc[0:3, 2]

print(filtro)

0    8.5
1    7.0
2    NaN
Name: Nota_Final, dtype: float64

## **SLIDE 03: tratamento e qualidade de dados**

### Atividade 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Dataframe com os dados
df = pd.DataFrame({
    'Nome': ['Alberto', 'Bárbara', 'Cláudia', 'Pedro', 'Rosa', 'Rui'],
    'Batimento': [65, 88, 74, np.nan, np.nan, 60],
    'Pressão': [132, 90, np.nan, 115, 86, 138],
    'Temperatura': [38, np.nan, 38, 36, 37, 39],
    'Sintoma': ['Nenhum', np.nan, np.nan, 'Dor no peito', np.nan, np.nan],
    'Diagnóstico': ['Doente', 'Saudável', 'Saudável', 'Doente', 'Saudável', 'Doente']
})

# Exibindo a tabela
print(df)

      Nome  Batimento  Pressão  Temperatura       Sintoma Diagnóstico
0  Alberto       65.0    132.0         38.0        Nenhum      Doente
1  Bárbara       88.0     90.0          NaN           NaN    Saudável
2  Cláudia       74.0      NaN         38.0           NaN    Saudável
3    Pedro        NaN    115.0         36.0  Dor no peito      Doente
4     Rosa        NaN     86.0         37.0           NaN    Saudável
5      Rui       60.0    138.0         39.0           NaN      Doente

In [ ]:
# Renomeação das colunas
df = df.rename(columns={
    'Nome': 'NOME',
    'Batimento': 'BATIMENTO',
    'Pressão': 'PRESSAO',
    'Temperatura': 'TEMPERATURA',
    'Sintoma': 'SINTOMA',
    'Diagnóstico': 'DIAGNOSTICO'
})


# Padronização textos
df['SINTOMA'] = df['SINTOMA'].str.strip().str.lower()
df['DIAGNOSTICO'] = df['DIAGNOSTICO'].str.strip().str.lower()

print(df)

      NOME  BATIMENTO  PRESSAO  TEMPERATURA       SINTOMA DIAGNOSTICO
0  Alberto       65.0    132.0         38.0        nenhum      doente
1  Bárbara       88.0     90.0          NaN           NaN    saudável
2  Cláudia       74.0      NaN         38.0           NaN    saudável
3    Pedro        NaN    115.0         36.0  dor no peito      doente
4     Rosa        NaN     86.0         37.0           NaN    saudável
5      Rui       60.0    138.0         39.0           NaN      doente

In [ ]:
# Criar uma cópia independente do DataFrame original
df2 = df.copy()

In [ ]:
# Criando o indicador de ausência (1 se for NaN, 0 se tiver valor)
# 'isna()': retorna True para valores ausentes e False para valores preenchidos
# 'astype(int)': converte True em 1 e False em 0

batimento_ausente = df2['BATIMENTO'].isna().astype(int)

# Inserindo a nova coluna na sequência (índice da coluna + 1)
df2.insert(loc=df2.columns.get_loc("BATIMENTO") + 1,
          column='BATIMENTO_AUS',
          value=batimento_ausente)

print(df2)

      NOME  BATIMENTO  BATIMENTO_AUS  PRESSAO  TEMPERATURA       SINTOMA  \
0  Alberto       65.0              0    132.0         38.0        nenhum
1  Bárbara       88.0              0     90.0          NaN           NaN
2  Cláudia       74.0              0      NaN         38.0           NaN
3    Pedro        NaN              1    115.0         36.0  dor no peito
4     Rosa        NaN              1     86.0         37.0           NaN
5      Rui       60.0              0    138.0         39.0           NaN

  DIAGNOSTICO
0      doente
1    saudável
2    saudável
3      doente
4    saudável
5      doente

In [ ]:
# Preencher valores ausentes da coluna "Batimento"

df2["BATIMENTO"] = df2["BATIMENTO"].fillna(round(df2["BATIMENTO"].median()))
#df2["BATIMENTO"] = df2["BATIMENTO"].fillna(round(df2.loc[df2['DIAGNOSTICO'] == 'doente', 'BATIMENTO'].mean()))

print(df2)

      NOME  BATIMENTO  BATIMENTO_AUS  PRESSAO  TEMPERATURA       SINTOMA  \
0  Alberto       65.0              0    132.0         38.0        nenhum
1  Bárbara       88.0              0     90.0          NaN           NaN
2  Cláudia       74.0              0      NaN         38.0           NaN
3    Pedro       70.0              1    115.0         36.0  dor no peito
4     Rosa       70.0              1     86.0         37.0           NaN
5      Rui       60.0              0    138.0         39.0           NaN

  DIAGNOSTICO
0      doente
1    saudável
2    saudável
3      doente
4    saudável
5      doente

In [ ]:
df3 = df2.copy()

# Tratamento da coluna Sintomas
sintoma_ausente = df3['SINTOMA'].isna().astype(int)

# Inserindo a nova coluna na sequência (índice da coluna + 1)
df3.insert(loc=df3.columns.get_loc("SINTOMA") + 1,
          column='SINTOMA_AUS',
          value=sintoma_ausente)

# Preencher valores ausentes
df3["SINTOMA"] = df3["SINTOMA"].fillna("sem sintoma")
print(df3)

      NOME  BATIMENTO  BATIMENTO_AUS  PRESSAO  TEMPERATURA       SINTOMA  \
0  Alberto       65.0              0    132.0         38.0        nenhum
1  Bárbara       88.0              0     90.0          NaN   sem sintoma
2  Cláudia       74.0              0      NaN         38.0   sem sintoma
3    Pedro       62.0              1    115.0         36.0  dor no peito
4     Rosa       62.0              1     86.0         37.0   sem sintoma
5      Rui       60.0              0    138.0         39.0   sem sintoma

   SINTOMA_AUS DIAGNOSTICO
0            0      doente
1            1    saudável
2            1    saudável
3            0      doente
4            1    saudável
5            1      doente

In [ ]:
# Faça o preenchimento dos valores ausentes das colunas Pressão e Temperatura

### Atividade 2

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniel', 'Ana', 'Elena', 'Fabio', 'Gisele'],
    'idade': [21, 176, 1, 26, 21, 41, 34, 28],
    'data_nascimento': ['1999-05-10', '1844-01-01', '2019-03-20', '1994-08-15', '1999-05-10', '1979-11-30', '1986-02-12', '1992-07-05'],
    'temperatura': [36.5, 37.0, -5.0, 36.8, 36.5, 41.5, 37.2, 36.6],
    'frequencia_cardiaca': [75, 80, 72, np.nan, 75, 110, 999, 82],
    'escolaridade': ['Graduação', 'Mestrado', 'Doutorado', 'Ensino Médio', 'Graduação', 'Graduação', 'Ensino Médio', 'Pós-graduação']
})

df.head(10)

In [ ]:
# Identifica e remove registros idênticos
print(df[df.duplicated(keep=False)])
df2 = df.drop_duplicates(keep='last')
print('\n', df2)

In [ ]:
df2 = df2.drop(columns=['data_nascimento'])
print(df2)

In [ ]:
# Tratamento de dados ausentes
# Contar quantos nulos existem por coluna
print("\nDiagnóstico de NaNs:\n", df2.isnull().sum(), '\n')

In [ ]:
# Tratamento de dados ausentes, inconsistentes e outliers
# Criando o indicador de ausência
frequencia_ausente = df2['frequencia_cardiaca'].isna().astype(int)
df2.insert(loc=df2.columns.get_loc("frequencia_cardiaca") + 1,
          column='FREQ_CARDIACA_AUS',
          value=frequencia_ausente)

# Preencher a frequência cardíaca vazia com a média
mediana_frequencia = round(df2['frequencia_cardiaca'].median())
df2['frequencia_cardiaca'] = df2['frequencia_cardiaca'].fillna(mediana_frequencia)

print(df2)

In [ ]:
df3 = df2

In [ ]:
# CORREÇÕES DE INCONSISTÊNCIAS E RUÍDOS

# Criando o indicador de dado corrigido
idade_corrigida = (df3['idade'] > 120).astype(int)
df3.insert(loc=df3.columns.get_loc("idade") + 1,
          column='IDADE_COR',
          value=idade_corrigida)

# Identificar e tratar idade impossível
media_idade = round(df3.loc[df3['idade'] <= 120, 'idade'].mean())
df3.loc[df3['idade'] > 120, 'idade'] = media_idade


# Identificar e tratar temperatura impossível (ex: < 30°C)
media_temp = round(df3.loc[df3['temperatura'] >= 30, 'temperatura'].mean(), 1)
df3.loc[df3['temperatura'] < 30, 'temperatura'] = media_temp


# Identificar e tratar ruído na frequência cardíaca
media_frequencia = round(df3.loc[df['frequencia_cardiaca'] <= 300, 'frequencia_cardiaca'].mean())
df3.loc[df['frequencia_cardiaca'] > 300, 'frequencia_cardiaca'] = media_frequencia

print(df3)

# **Aula 03 (23/10): Transformação de dados e escalas**

## **SLIDE 04: transformações de dados e escalas**

### Conversão

**CONVERSÃO: quali => quanti**

In [ ]:
######################################
## CONVERSÃO: ORDINAL PARA NUMÉRICO ##
######################################

import pandas as pd

# Criação do DataFrame
df = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00, 'Quinto', 'Não'],
        ['São Paulo', 'São Carlos', 254484, 1508.00, 'Quarto', 'Não'],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00, 'Segundo', 'Sim'],
        ['Paraná', 'Curitiba', 1963726, 2293.00, 'Primeiro', 'Sim'],
        ['São Paulo', 'Campinas', 1223237, 1710.00, 'Terceiro', 'Não']
    ],
    columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio',
             'Classificação', 'Capital']
)

print(df)

           Estado         Cidade  Habitantes  Salário-Médio Classificação  \
0          Paraná       Londrina      575377         1356.0        Quinto
1       São Paulo     São Carlos      254484         1508.0        Quarto
2  Santa Catarina  Florianópolis      508826         1798.0       Segundo
3          Paraná       Curitiba     1963726         2293.0      Primeiro
4       São Paulo       Campinas     1223237         1710.0      Terceiro

  Capital
0     Não
1     Não
2     Sim
3     Sim
4     Não

In [ ]:
# Importando a função de transformação ordinal do scikit-learn
from sklearn.preprocessing import OrdinalEncoder

ordem = ['Primeiro', 'Segundo', 'Terceiro', 'Quarto', 'Quinto']
codificador = OrdinalEncoder(categories=[ordem])  # atribui valores numéricos baseados na ordem da lista
df['Clas_convertida'] = codificador.fit_transform(df[['Classificação']])

print(df)

           Estado         Cidade  Habitantes  Salário-Médio Classificação  \
0          Paraná       Londrina      575377         1356.0        Quinto
1       São Paulo     São Carlos      254484         1508.0        Quarto
2  Santa Catarina  Florianópolis      508826         1798.0       Segundo
3          Paraná       Curitiba     1963726         2293.0      Primeiro
4       São Paulo       Campinas     1223237         1710.0      Terceiro

  Capital  Clas_convertida
0     Não              4.0
1     Não              3.0
2     Sim              1.0
3     Sim              0.0
4     Não              2.0

In [ ]:
######################################
## CONVERSÃO: NOMINAL PARA NUMÉRICO ##
######################################

from sklearn.preprocessing import OneHotEncoder

# criar uma coluna binária para cada categoria única encontrada
encoder = OneHotEncoder()

# transformar a coluna categórica em uma matriz binária (Dummificação)
estados = encoder.fit_transform(df[['Estado']]).toarray()

# converte a matriz de números binários em um DataFrame do Pandas
estados_df = pd.DataFrame(estados, columns=encoder.categories_[0])

# Concatenando as novas colunas e removendo a coluna original
df = pd.concat([df, estados_df], axis=1)
df.drop('Estado', axis=1, inplace=True)

#print(df)
print(df)

          Cidade  Habitantes  Salário-Médio Classificação Capital  \
0       Londrina      575377         1356.0        Quinto     Não
1     São Carlos      254484         1508.0        Quarto     Não
2  Florianópolis      508826         1798.0       Segundo     Sim
3       Curitiba     1963726         2293.0      Primeiro     Sim
4       Campinas     1223237         1710.0      Terceiro     Não

   Clas_convertida  Paraná  Santa Catarina  São Paulo
0              4.0     1.0             0.0        0.0
1              3.0     0.0             0.0        1.0
2              1.0     0.0             1.0        0.0
3              0.0     1.0             0.0        0.0
4              2.0     0.0             0.0        1.0

**CONVERSÃO: quanti => quali**

In [ ]:
######################################
## CONVERSÃO: NUMÉRICO PARA ORDINAL ##
######################################

# Criando o DataFrame de idade
df = pd.DataFrame({'Idade': [42, 15, 67, 55,
                            1, 29, 75, 89, 4,
                            10, 15, 38, 22, 77]})

print(df)

    Idade
0      42
1      15
2      67
3      55
4       1
5      29
6      75
7      89
8       4
9      10
10     15
11     38
12     22
13     77

In [ ]:
# Criar uma nova coluna agrupando as idades em classes
df['Label'] = pd.cut(x=df['Idade'],
                     bins=[0, 3, 17, 70, 99],
                     labels=['Bebê', 'Criança', 'Adulto', 'Idoso'])

print(df)

    Idade    Label
0      42   Adulto
1      15  Criança
2      67   Adulto
3      55   Adulto
4       1     Bebê
5      29   Adulto
6      75    Idoso
7      89    Idoso
8       4  Criança
9      10  Criança
10     15  Criança
11     38   Adulto
12     22   Adulto
13     77    Idoso

**ATIVIDADE: Conversão**

In [ ]:
import pandas as pd
import numpy as np

# Dataset para atividade de conversão (Quali <-> Quanti)
dados = {
    'ID_Paciente': [101, 102, 103, 104, 105, 106, 107],

    # 1. Quali Ordinal -> converter em Quanti
    'Satisfacao_Atendimento': ['Ruim', 'Regular', 'Bom', 'Excelente', 'Bom', 'Ruim', 'Excelente'],

    # 2. Quali Nominal -> converter em Quanti
    'Setor_Hospital': ['Emergência', 'UTI', 'Enfermaria', 'Emergência', 'UTI', 'Enfermaria', 'Emergência'],

    # 3. Quanti -> converter em Quali
    'Idade': [12, 28, 45, 68, 82, 34, 5],

    # 4. Quanti -> converter em Quali
    'Temperatura_C': [36.5, 37.8, 38.6, 39.2, 36.6, 38.1, 37.0]
}

df_exercicio = pd.DataFrame(dados)
print(df_exercicio)

   ID_Paciente Satisfacao_Atendimento Setor_Hospital  Idade  Temperatura_C
0          101                   Ruim     Emergência     12           36.5
1          102                Regular            UTI     28           37.8
2          103                    Bom     Enfermaria     45           38.6
3          104              Excelente     Emergência     68           39.2
4          105                    Bom            UTI     82           36.6
5          106                   Ruim     Enfermaria     34           38.1
6          107              Excelente     Emergência      5           37.0

In [ ]:
# 1. Quali Ordinal -> converter em Quanti

ordem = ['Primeiro', 'Segundo', 'Terceiro', 'Quarto', 'Quinto']
codificador = OrdinalEncoder(categories=[ordem])  # atribui valores numéricos baseados na ordem da lista
df['Clas_convertida'] = codificador.fit_transform(df[['Satisfacao_Atendimento']])

print(df)

### Transformação

**Funções Matemáticas**

In [ ]:
import pandas as pd
import numpy as np

dados = {
    'Rendimento_Anual': [12000, 45000, 180000, 2500000],
    'Erros_Producao': [0, 4, 9, 25],
    'Tempo_Conclusao_Min': [2, 5, 10, 20],
    'Variacao_Temperatura': [-5.2, 3.1, -1.8, 0.4]
}

df = pd.DataFrame(dados)

# 1. Logarítmica
df['Rendimento_Log'] = np.log(df['Rendimento_Anual'])

# 2. Raiz Quadrada
df['Erros_Raiz'] = np.sqrt(df['Erros_Producao'])

# 3. Recíproco
df['Taxa_Produtividade'] = 1 / df['Tempo_Conclusao_Min']

# 4. Módulo
df['Variacao_Absoluta'] = df['Variacao_Temperatura'].abs()

df.head()

,Rendimento_Anual,Erros_Producao,Tempo_Conclusao_Min,Variacao_Temperatura,Rendimento_Log,Erros_Raiz,Taxa_Produtividade,Variacao_Absoluta
0,12000,0,2,-5.2,9.392662,0.0,0.50,5.2
1,45000,4,5,3.1,10.714418,2.0,0.20,3.1
2,180000,9,10,-1.8,12.100712,3.0,0.10,1.8
3,2500000,25,20,0.4,14.731801,5.0,0.05,0.4

In [ ]:
# Lista fixa com 100 salários
salarios_fixos = [
    # Faixa Inicial
    1412.00, 1450.00, 1500.00, 1550.00, 1600.00, 1650.00, 1700.00, 1750.00, 1800.00, 1850.00,
    1900.00, 1950.00, 2000.00, 2050.00, 2100.00, 2150.00, 2200.00, 2250.00, 2300.00, 2350.00,
    2400.00, 2450.00, 2500.00, 2600.00, 2700.00, 2800.00, 2900.00, 3000.00, 3100.00, 3200.00,
    # Faixa Plena
    3300.00, 3400.00, 3500.00, 3600.00, 3700.00, 3800.00, 3900.00, 4000.00, 4200.00, 4400.00,
    4600.00, 4800.00, 5000.00, 5200.00, 5400.00, 5600.00, 5800.00, 6000.00, 6200.00, 6400.00,
    6600.00, 6800.00, 7000.00, 7200.00, 7400.00, 7600.00, 7800.00, 8000.00, 8300.00, 8600.00,
    # Faixa Sênior
    8900.00, 9200.00, 9500.00, 9800.00, 10200.00, 10600.00, 11000.00, 11500.00, 12000.00, 12500.00,
    13000.00, 13500.00, 14000.00, 14500.00, 15000.00, 15800.00, 16600.00, 17400.00, 18200.00, 19000.00,
    20000.00, 21000.00, 22000.00, 23000.00, 24000.00,
    # Faixa de Liderança
    25000.00, 27000.00, 29000.00, 31000.00, 33000.00, 35000.00, 38000.00, 41000.00, 45000.00, 50000.00,
    55000.00, 62000.00, 70000.00, 85000.00, 110000.00
]

# Criando o DataFrame
df = pd.DataFrame({'Salario': salarios_fixos})

# Aplicando as transformações
df['Log_X'] = np.log(df['Salario'])
df['Raiz_X'] = np.sqrt(df['Salario'])
df['1/X'] = 1 / df['Salario']

# Função de cálculo estatístico
def calcular_estatisticas(dataframe):
    resumo = []
    for coluna in dataframe.columns:
        media = dataframe[coluna].mean()
        desvio = dataframe[coluna].std()
        resumo.append({
            'Transformação': coluna,
            'CV (%)': round((desvio / media) * 100, 2),
            'Assimetria': round(dataframe[coluna].skew(), 2),
            'Curtose': round(dataframe[coluna].kurt(), 2)
        })
    return pd.DataFrame(resumo)

# Exibindo os resultados estatísticos
print(calcular_estatisticas(df).to_string(index=False))

Transformação  CV (%)  Assimetria  Curtose
      Salario  137.01        2.87     9.80
        Log_X   12.32        0.46    -0.65
       Raiz_X   61.74        1.55     2.40
          1/X   85.91        0.85    -0.42

**Normalização**

In [ ]:
import pandas as pd

dados = {
    'Candidato': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo'],
    'Anos_Experiencia': [1, 3, 5, 8, 10],
    'Pontuacao_Teste': [400, 550, 700, 850, 1000]
}
df = pd.DataFrame(dados)
df.head()

  Candidato  Anos_Experiencia  Pontuacao_Teste
0       Ana                 1              400
1     Bruno                 3              550
2    Carlos                 5              700
3   Daniela                 8              850
4   Eduardo                10             1000

In [ ]:
# Aplicar as transformações na coluna 'Pontuacao_Teste'
x = df['Pontuacao_Teste']
min_x = x.min()
max_x = x.max()
media_x = x.mean()
desvio_x = x.std()

# 1. Normalização pelo Máximo
df['Teste_Max'] = x / max_x

# 2. Normalização Min-Max ([0, 1])
df['Teste_MinMax'] = (x - min_x) / (max_x - min_x)

# 3. Escalonamento em Intervalo Personalizado [a, b]
a, b = -2, 2
df['Teste_Intervalo'] = a + ((x - min_x) * (b - a)) / (max_x - min_x)

# 4. Padronização Z-Score (Média = 0, Desvio Padrão = 1)
df['Teste_ZScore'] = (x - media_x) / desvio_x


print(df[['Candidato', 'Pontuacao_Teste', 'Teste_Max', 'Teste_MinMax',
          'Teste_Intervalo', 'Teste_ZScore']].round(3))

  Candidato  Pontuacao_Teste  Teste_Max  Teste_MinMax  Teste_Intervalo  \
0       Ana              400       0.40          0.00             -2.0
1     Bruno              550       0.55          0.25             -1.0
2    Carlos              700       0.70          0.50              0.0
3   Daniela              850       0.85          0.75              1.0
4   Eduardo             1000       1.00          1.00              2.0

   Teste_ZScore
0        -1.265
1        -0.632
2         0.000
3         0.632
4         1.265

In [ ]:
# Aplicando a função MinMaxScaler da biblioteca SKlearn
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({'Valores': [1, 18, 0.5, 20, 10, 0.1, 15]})

scaler = MinMaxScaler(feature_range=(0, 10))
df_minmax = pd.DataFrame(scaler.fit_transform(df), columns=df.columns).round(2)

print(df_minmax)

   Valores
0     0.45
1     8.99
2     0.20
3    10.00
4     4.97
5     0.00
6     7.49

In [ ]:
# Aplicando a normalização Z-score pela função StandardScaler da SKlearn
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame({'Valores': [1, 18, 0.5, 20, 10, 0.1, 15]})

scaler = StandardScaler()
df_normal = pd.DataFrame(scaler.fit_transform(df), columns=df.columns).round(2)

print(df_normal)

   Valores
0    -1.02
1     1.09
2    -1.08
3     1.34
4     0.10
5    -1.13
6     0.72

In [ ]:
import numpy as np
from sklearn.preprocessing import RobustScaler, StandardScaler, MinMaxScaler

dados = {
    'Funcionario': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo', 'Fernanda',
                    'Gabriel', 'Helena', 'Pedro', 'Alberto'],
    'Horas_Estudo': [2, 3, 3, 4, 4, 5, 5, 6, 45, 60],
    'Salario_k': [3.5, 4.0, 4.2, 4.5, 5.0, 5.2, 5.5, 6.0, 85.0, 51.0]
}

df = pd.DataFrame(dados)

# Instanciando os escaladores para comparação
robust = RobustScaler()
standard = StandardScaler()
minmax = MinMaxScaler()

# Aplicando as transformações na coluna 'Salario_k'
coluna = df[['Salario_k']]

df['Salario_Robust'] = robust.fit_transform(coluna).round(2)
df['Salario_Standard'] = standard.fit_transform(coluna).round(2)
df['Salario_MinMax'] = minmax.fit_transform(coluna).round(2)

print(df[['Funcionario', 'Salario_k', 'Salario_Robust', 'Salario_Standard',
          'Salario_MinMax']])

  Funcionario  Salario_k  Salario_Robust  Salario_Standard  Salario_MinMax
0         Ana        3.5           -1.00             -0.53            0.00
1       Bruno        4.0           -0.69             -0.51            0.01
2      Carlos        4.2           -0.56             -0.50            0.01
3     Daniela        4.5           -0.37             -0.49            0.01
4     Eduardo        5.0           -0.06             -0.47            0.02
5    Fernanda        5.2            0.06             -0.46            0.02
6     Gabriel        5.5            0.25             -0.45            0.02
7      Helena        6.0            0.56             -0.43            0.03
8       Pedro       85.0           49.94              2.56            1.00
9     Alberto       51.0           28.69              1.27            0.58

In [ ]:
# Aplicando primeiro a transformação logarítmica
df['Salario_Log'] = np.log(df['Salario_k'])

# Instanciando os escaladores
minmax = MinMaxScaler()
standard = StandardScaler()
robust = RobustScaler()

# Aplicando os escaladores sobre a coluna transformada em log
df['Log_MinMax'] = minmax.fit_transform(df[['Salario_Log']]).round(2)
df['Log_Standard'] = standard.fit_transform(df[['Salario_Log']]).round(2)
df['Log_Robust'] = robust.fit_transform(df[['Salario_Log']]).round(2)

# Exibindo o resultado comparativo
print(df[['Funcionario', 'Salario_k', 'Salario_Log', 'Log_MinMax',
          'Log_Standard', 'Log_Robust']].round(2))

  Funcionario  Salario_k  Salario_Log  Log_MinMax  Log_Standard  Log_Robust
0         Ana        3.5         1.25        0.00         -0.76       -1.18
1       Bruno        4.0         1.39        0.04         -0.64       -0.76
2      Carlos        4.2         1.44        0.06         -0.59       -0.61
3     Daniela        4.5         1.50        0.08         -0.53       -0.39
4     Eduardo        5.0         1.61        0.11         -0.43       -0.06
5    Fernanda        5.2         1.65        0.12         -0.39        0.06
6     Gabriel        5.5         1.70        0.14         -0.34        0.24
7      Helena        6.0         1.79        0.17         -0.26        0.51
8       Pedro       85.0         4.44        1.00          2.21        8.86
9     Alberto       51.0         3.93        0.84          1.73        7.25

# **Aula 04 (30/10): Fundamentos de visualização estatística de dados**

## **SLIDE 05: visualização estatística de dados**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

### Gráfico de Barras/colunas

In [ ]:
# 1. Preparação dos dados
cidades = ['Blumenau', 'Gaspar', 'Indaial', 'Timbó']
frequencias = [23, 18, 12, 10]

# 2. Criação da figura
plt.figure(figsize=(6, 3))

# 3. Plotagem do gráfico de barras
plt.bar(cidades,            # variável x do gráfico
        frequencias,        # variável y do gráfico
        color='skyblue',
        edgecolor='black')

# 4. Elementos de identificação
plt.title('Distribuição dos alunos de BCD por cidade de origem (2026)',
          fontsize=12,
          fontweight='bold',
          pad=10)
plt.xlabel('Cidades', fontsize=8)
plt.ylabel('Frequência absoluta', fontsize=8)

# 5. Definir a escala do eixo Y
plt.ylim(0, max(frequencias)+3)

# 6. Adicionando linhas de grade
plt.grid(axis='y', linestyle='--', alpha=0.3)

# 7. Exibição do gráfico
plt.tight_layout()

# Salvando a imagem
plt.savefig("Gráfico de Barras.jpeg", dpi=300)

plt.show()

In [ ]:
# Carrega o dataset de cidades brasileiras
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Agrupa os municípios por estado e calcula a média do PIB de cada estado
dados = df_brasil.groupby(by=['STATE'])['GDP_CAPITA'].mean()

# Gera o gráfico de barras a partir da série resultante do groupby
# OBS.: o pandas já usa o índice (estados) como eixo X automaticamente
ax = dados.plot.bar(figsize=(10, 5))

# Customizar gráfico: define os rótulos dos eixos
ax.set(xlabel='Estados', ylabel='Produto interno Bruto (PIB) per capita')

plt.tight_layout()
plt.show()

In [ ]:
# Gera o gráfico de barras com matplotlib 'plt'
plt.figure(figsize=(10, 5))
plt.bar(dados.index, dados.values
        color='#A8D8B9',
        edgecolor='#4A9B6E',
        linewidth=1.2)

# Customizar gráfico: rótulos dos eixos em negrito
plt.xlabel('Estados', fontweight='bold', fontsize=9)
plt.ylabel('PIB per capita', fontweight='bold', fontsize=9)
plt.title('PIB per capita dos estados brasileiros do ano de 2016',
          fontweight='bold',
          fontsize=16)

# Grade de fundo
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.gca().set_axisbelow(True)

plt.tight_layout()
plt.show()

In [ ]:
# Carregar o arquivo de dados
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Criar a coluna 'REGION' no DataFrame
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Agrupar os dados por região (contagem de cidades e soma da população)
data = df_brasil.groupby(by=['REGION']).agg({
    'CITY': 'count',
    'IBGE_RES_POP': 'sum'
})

# Converter os valores absolutos para porcentagem em relação ao total do país
data['CITY'] = (data['CITY'] / data['CITY'].sum()) * 100
data['IBGE_RES_POP'] = (data['IBGE_RES_POP'] /
                           data['IBGE_RES_POP'].sum()) * 100

# Gerar o gráfico de barras horizontais
ax = data.plot.barh(figsize=(8, 5))

ax.set(xlabel='Porcentagem com relação ao Brasil (%)', ylabel='Região')

# Definir a legenda do gráfico
ax.legend(['Porcentagem de cidades por região no Brasil',
           'Porcentagem de pessoas por região no Brasil'])

plt.tight_layout()
plt.show()

### Gráfico de setor

In [ ]:
# 1. Dados
cidades = ['Blumenau', 'Gaspar', 'Indaial', 'Timbó']
frequencias = [23, 12, 8, 5]
cores = ['#ff9999','#66b3ff','#99ff99','#ffcc99']

# 2. Configuração da figura
plt.figure(figsize=(5, 5))

# 3. Criando o gráfico de pizza
plt.pie(frequencias,
        labels=cidades,        # Nomes das cidades nas fatias
        autopct='%1.1f%%',     # Formata e exibe a porcentagem automaticamente
        startangle=90,         # Rotaciona o gráfico para começar no topo (12h)
        colors=cores,          # Aplica a paleta de cores
        pctdistance=0.85)      # Distância da porcentagem em relação ao centro

# 4. Título
plt.title('Proporção de alunos por cidade de origem', fontsize=14,
          fontweight='bold', pad=10)

# 5. Exibição
plt.tight_layout()
plt.show()

In [ ]:
# Carrega o dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Cria a coluna 'REGION' no DataFrame, mapeando cada estado para sua região
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Define uma cor fixa para cada região
colors = ['lightskyblue', 'red', 'blue', 'green', 'gold']

# Cria uma figura com 1 linha e 2 colunas de gráficos
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15, 7))

# Primeiro gráfico de setores: soma de impostos (TAXES) por região
data_taxes = df_brasil.groupby(by=['REGION'])['TAXES'].sum()
data_taxes.plot.pie(colors=colors, autopct='%1.1f%%', ax=axes[0])
# autopct='%1.1f%%' calcula e exibe a porcentagem de cada fatia automaticamente

# Segundo gráfico de setores: soma do PIB (GDP) por região
data_gdp = df_brasil.groupby(by=['REGION'])['GDP'].sum()
data_gdp.plot.pie(colors=colors, autopct='%1.1f%%', ax=axes[1])

# Customização: definir os títulos de cada gráfico
axes[0].set_title('Distribuição do volume de impostos pagos por região do Brasil em 2016')
axes[1].set_title('Distribuição do PIB por região do Brasil em 2016')

plt.tight_layout()
plt.show()

### Gráfico de Dispersão

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Criar a coluna 'REGION' no DataFrame
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Filtragem dos dados (removendo municípios com gasto zero ou ausente)
data = df_brasil.query("MUN_EXPENDIT != 0").dropna(subset=['IDHM',
                                                           'MUN_EXPENDIT',
                                                           'REGION'])

# Configuração da figura
plt.subplots(figsize=(10, 6))

# Definição do eixo Y para escala logarítmica devido à alta amplitude dos gastos
plt.yscale('log')

# Construção do gráfico de dispersão
sct_plot = sns.scatterplot(
    data=data,
    x='IDHM',          # eixo horizontal
    y='MUN_EXPENDIT',  # eixo vertical
    hue='REGION'       # dimensão qualitativa adicional
)

# Formatação dos rótulos e títulos dos eixos
sct_plot.set_xlabel('IDH do município', fontsize=12)
sct_plot.set_ylabel('Gastos do município', fontsize=12)

# Ajuste de layout e exibição
plt.tight_layout()
plt.show()

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Criar a coluna 'REGION' no DataFrame
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Filtragem de dados (removendo registros ausentes ou com despesa zero)
data = df_brasil.query("MUN_EXPENDIT != 0").dropna(subset=['LONG', 'LAT',
                                                           'IDHM',
                                                           'MUN_EXPENDIT'])

# Configuração da figura
plt.subplots(figsize=(8, 8))

# Construção do gráfico de dispersão espacial
# - x: Longitude (eixo horizontal)
# - y: Latitude (eixo vertical)
# - hue: IDHM (cor do ponto variando conforme o IDH)
# - size: MUN_EXPENDIT (tamanho do ponto variando conforme o volume de gastos)
sns.scatterplot(
    x=data.LONG,
    y=data.LAT,
    hue=data['IDHM'],
    size=data['MUN_EXPENDIT']
)

# Ajuste dos rótulos dos eixos e exibição
plt.xlabel('LONG')
plt.ylabel('LAT')

plt.tight_layout()
plt.show()

### Gráfico de Linhas

In [ ]:
# 1. Dados
avaliacoes = ['Prova 1', 'Prova 2', 'Prova 3', 'Prova 4']
notas_medias = [6.5, 7.2, 3.8, 8.5]

# 2. Criando o gráfico de linhas
plt.figure(figsize=(7, 5))
plt.plot(avaliacoes,
         notas_medias,
         marker='o', linestyle='--',
         color='green', linewidth=3)

# 3. Elementos do gráfico
plt.title('Evolução do desempenho médio da turma de BCD \nnas avaliações de 2026/2',
          fontsize=14, fontweight='bold')
plt.xlabel('Avaliações ao longo do semestre', fontsize=12)
plt.ylabel('Nota Média', fontsize=12)
plt.ylim(0, 10)

# 4. Estética
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Agrupamento por estado (STATE) e soma das populações de 2010 e 2018
data = df_brasil.groupby('STATE')[['IBGE_RES_POP',
                                   'ESTIMATED_POP']].sum(numeric_only=True)

# Construção do gráfico de linhas
plt.figure(figsize=(12, 5))

plt.plot(data.index, data['IBGE_RES_POP'], linestyle='--',
         label='População 2010 (Censo)', marker='o')
plt.plot(data.index, data['ESTIMATED_POP'], linestyle='--',
         label='População 2018 (Estimativa)', marker='s')

# Customização
plt.xticks(rotation=45) # rotação dos rótulos do eixo X
plt.xlabel('Estados')
plt.ylabel('População')
plt.legend()

plt.tight_layout()
plt.show()

### Gráfico de Radar

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Cria a coluna 'REGION' no DataFrame, mapeando cada UF (estado) para sua região
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}
df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Seleciona as variáveis que vamos comparar no radar:
variaveis_idhm = ['IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao']
variaveis_gva = ['GVA_AGROPEC', 'GVA_INDUSTRY', 'GVA_SERVICES', 'GVA_PUBLIC']

# Calcula a média de cada variável, agrupando os municípios por região
dados = df_brasil.groupby('REGION')[variaveis_idhm + variaveis_gva].mean()

# O IDHM está em escala 0-1, enquanto o GVA será convertido para %.
# Multiplicar por 100 coloca o IDHM na mesma ordem de grandeza das demais
# variáveis, para nenhum eixo "dominar" o gráfico por causa da escala.
dados[variaveis_idhm] = dados[variaveis_idhm] * 100

# O GVA vem em valores monetários brutos, que variam muito entre regiões
# Por isso, convertemos cada setor para sua % de participação dentro da própria região.
dados['GVA_TOTAL'] = dados[variaveis_gva].sum(axis=1)
for col in variaveis_gva:
    dados[col] = (dados[col] / dados['GVA_TOTAL']) * 100
dados = dados.drop(columns='GVA_TOTAL')  # coluna auxiliar não é mais necessária

# Seleciona apenas 3 regiões para não poluir o gráfico com muitos polígonos
dados = dados.loc[['Sul', 'Nordeste', 'Sudeste']]

# Define os ângulos dos eixos do radar
categorias = list(dados.columns)
n_vars = len(categorias)   # quantidade de eixos
# criar sequência de número igualmente espaçados entre 0 e 2pi
angulos = np.linspace(0, 2*np.pi, n_vars, endpoint=False).tolist()
angulos += angulos[:1]  # repete o primeiro ângulo no final para fechar o polígono

fig, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True)) #definir malhar polar
cores = {'Sul': '#5B8FF9', 'Nordeste': '#F98C5C', 'Sudeste': '#5AD8A6'}

# Desenha um polígono por região
for regiao in dados.index:
    valores = dados.loc[regiao].tolist()
    valores += valores[:1]
    ax.plot(angulos, valores, linewidth=2, label=regiao, color=cores[regiao])
    ax.fill(angulos, valores, alpha=0.1, color=cores[regiao])

# Configura os rótulos de cada eixo (nome das variáveis ao redor do círculo)
ax.set_xticks(angulos[:-1])
ax.set_xticklabels(categorias, fontsize=9)
ax.set_yticklabels([])  # oculta os valores numéricos do raio
ax.set_title('Perfil comparativo entre regiões: IDH e composição econômica (%)',
             fontsize=12, pad=20)
ax.legend(loc='best')

plt.tight_layout()
plt.show()

In [ ]:
import plotly.graph_objects as go

# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Cria a coluna 'REGION'
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}
df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Tratamento de colunas numéricas: algumas podem vir como texto,
# usando vírgula como separador decimal (padrão brasileiro) em vez de ponto
colunas_analise = ['ESTIMATED_POP', 'AREA', 'GDP', 'COMP_TOT', 'TAXES']

for col in colunas_analise:
    if col in df_brasil.columns:
        if df_brasil[col].dtype == 'object':  # coluna veio como texto
            df_brasil[col] = df_brasil[col].astype(str).str.replace(',', '.')
        #Converte para número; valores que não puderem ser convertidos viram NaN
        df_brasil[col] = pd.to_numeric(df_brasil[col], errors='coerce')

# Agrupa os municípios por região e soma os 6 atributos de interesse
data = df_brasil.groupby(by=['REGION']).agg({
    'CITY': 'count',           # número de municípios na região
    'ESTIMATED_POP': 'sum',
    'AREA': 'sum',
    'GDP': 'sum',
    'COMP_TOT': 'sum',
    'TAXES': 'sum'
})

# Renomeia as colunas para rótulos mais legíveis
data.columns = ['Cidades', 'População', 'Área', 'PIB', 'Empresas', 'Impostos']

# Normalização: cada coluna passa a somar 1 (100%) entre as 5 regiões.
for col in data.columns:
    data[col] = data[col] / sum(data[col])

# Constrói o gráfico de radar interativo com Plotly.
# Cada go.Scatterpolar desenha um polígono (uma região):
#   r = valores da região naquela linha (raio de cada eixo)
#   theta = nomes das variáveis (posição angular de cada eixo)
#   fill='toself' preenche a área do polígono
#   name = nome da região, usado na legenda
fig = go.Figure(
    data=[
        go.Scatterpolar(r=data.values[0], theta=data.columns, fill='toself', name=data.index[0]),
        go.Scatterpolar(r=data.values[1], theta=data.columns, fill='toself', name=data.index[1]),
        go.Scatterpolar(r=data.values[2], theta=data.columns, fill='toself', name=data.index[2]),
        go.Scatterpolar(r=data.values[3], theta=data.columns, fill='toself', name=data.index[3]),
        go.Scatterpolar(r=data.values[4], theta=data.columns, fill='toself', name=data.index[4]),
    ],
    layout=go.Layout(
        title='Proporção de Atributos Socioeconômicos por Região do Brasil',
        polar={'radialaxis': {'visible': True}},  # mostra a régua radial (0 a 1) no fundo do gráfico
        showlegend=True
    )
)

# Exibe o gráfico interativo (funciona em notebook Jupyter ou navegador)
fig.show()

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Cria a coluna 'REGION'
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}
df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Tratamento de colunas numéricas: algumas podem vir como texto,
# usando vírgula como separador decimal (padrão brasileiro) em vez de ponto
colunas_analise = ['ESTIMATED_POP', 'AREA', 'GDP', 'COMP_TOT', 'TAXES']

for col in colunas_analise:
    if col in df_brasil.columns:
        if df_brasil[col].dtype == 'object':  # coluna veio como texto
            df_brasil[col] = df_brasil[col].astype(str).str.replace(',', '.')
        # Converte para número; valores que não puderem ser convertidos viram NaN (errors='coerce')
        df_brasil[col] = pd.to_numeric(df_brasil[col], errors='coerce')

# Agrupa os municípios por região e soma os atributos de interesse
data = df_brasil.groupby(by=['REGION']).agg({
    'CITY': 'count',           # número de municípios na região
    'ESTIMATED_POP': 'sum',
    'AREA': 'sum',
    'GDP': 'sum',
    'COMP_TOT': 'sum',
    'TAXES': 'sum'
})

# Renomeia as colunas para rótulos mais legíveis
data.columns = ['Cidades', 'População', 'Área', 'PIB', 'Empresas', 'Impostos']

# Normalização: cada coluna passa a somar 1 (100%) entre as 5 regiões.
for col in data.columns:
    data[col] = data[col] / sum(data[col])

# Define os ângulos dos eixos do radar: um eixo por variável, distribuídos igualmente no círculo
categorias = list(data.columns)
n_vars = len(categorias)
angulos = np.linspace(0, 2 * np.pi, n_vars, endpoint=False).tolist()
angulos += angulos[:1]  # repete o primeiro ângulo no final, para "fechar" o polígono

fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))

# Lista de cores para desenhar cada região com uma cor diferente
cores = ['#5B8FF9', '#F98C5C', '#5AD8A6', '#E86452', '#9270CA']

# Desenha um polígono por região
for i, regiao in enumerate(data.index):
    valores = data.loc[regiao].tolist()
    valores += valores[:1]
    ax.plot(angulos, valores, linewidth=2, label=regiao, color=cores[i % len(cores)])
    ax.fill(angulos, valores, alpha=0.15, color=cores[i % len(cores)])  # preenchimento leve, para destacar a área

# Configura os rótulos de cada eixo
ax.set_xticks(angulos[:-1])
ax.set_xticklabels(categorias, fontsize=11)
ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1))

plt.tight_layout()
plt.show()

### Gráfico de Coordenadas Paralelas

In [ ]:
from pandas.plotting import parallel_coordinates

# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Cria a coluna 'REGION' no DataFrame
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}
df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Seleciona só as colunas que vamos usar e remove municípios com algum valor faltando
colunas = ['IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'ESTIMATED_POP', 'GDP', 'REGION']
# sample(100) pega 100 municípios aleatórios, para o gráfico não ficar poluído
amostra = df_brasil[colunas].dropna().sample(100, random_state=1)

# Normalização min-max (0 a 1) de cada variável quantitativa.
variaveis_num = ['IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'ESTIMATED_POP', 'GDP']
amostra_norm = amostra.copy()
for col in variaveis_num:
    amostra_norm[col] = (amostra[col] - amostra[col].min()) / (amostra[col].max() - amostra[col].min())

# Construção do gráfico de coordenadas paralelas.
# A função parallel_coordinates já vem pronta no pandas - não é preciso desenhar
# os eixos manualmente (diferente do gráfico de radar, feito com matplotlib puro).
fig, ax = plt.subplots(figsize=(11, 6))
parallel_coordinates(
    amostra_norm,
    class_column='REGION',   # coluna categórica usada para colorir cada linha
    cols=variaveis_num,      # variáveis que formam os eixos verticais, na ordem desejada
    ax=ax,
    alpha=0.5                # transparência nas linhas, para reduzir a sobreposição visual
)

# Posiciona a legenda um pouco para fora da área do gráfico, à direita
ax.legend(loc='upper right', bbox_to_anchor=(1.25, 1))

plt.tight_layout()
plt.show()

In [ ]:
import plotly.graph_objects as go

# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Mapeamento das regiões
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Filtrar apenas os municípios das regiões Sul e Nordeste
data = df_brasil.query("REGION == 'Sul' or REGION == 'Nordeste'").copy()

# Limpeza e conversão dos campos numéricos
for col in ['AREA', 'GDP_CAPITA', 'ESTIMATED_POP']:
    if data[col].dtype == 'object':
        data[col] = data[col].astype(str).str.replace(',', '.')
    data[col] = pd.to_numeric(data[col], errors='coerce')

# Remove municípios com algum valor faltando nas colunas que vamos usar
data = data.dropna(subset=['AREA', 'ESTIMATED_POP', 'RURAL_URBAN',
                           'GDP_CAPITA', 'REGION'])

# Mapeamento categórico das variáveis nominais
category_rural_urban = data['RURAL_URBAN'].astype('category').cat
category_region = data['REGION'].astype('category').cat

# Geração do gráfico de Coordenadas Paralelas
fig = go.Figure(
    data=go.Parcoords(
        # Define a cor de cada linha a partir do código numérico da região
        line = dict(
            color = category_region.codes,
            colorscale = [[0, 'royalblue'], [1, 'crimson']]
        ),
        # Cada item da lista abaixo é um eixo do gráfico
        dimensions = list([
            # Eixos numéricos
            dict(label = 'Área Total Média', values = data['AREA']),
            dict(label = 'População em 2018', values = data['ESTIMATED_POP']),
            dict(label = 'PIB per capita', values = data['GDP_CAPITA']),
            # Eixo categórico
            # tickvals/ticktext fazem o eixo MOSTRAR o nome da categoria
            dict(
                tickvals = list(range(len(category_rural_urban.categories))),
                ticktext = category_rural_urban.categories,
                label = 'Tipologia Rural/Urbano',
                values = category_rural_urban.codes
            ),
            dict(
                label = "Região",
                tickvals = list(range(len(category_region.categories))),
                ticktext = category_region.categories,
                values = category_region.codes
            ),
        ])
    )
)


fig.show()

### Histograma

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Mapeamento das regiões
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Remover municípios sem valor de IDHM
data = df_brasil.dropna(subset=['IDHM'])

# Separar um DataFrame por região
norte = data[data['REGION'] == 'Norte']
nordeste = data[data['REGION'] == 'Nordeste']
centro_oeste = data[data['REGION'] == 'Centro-Oeste']
sudeste = data[data['REGION'] == 'Sudeste']
sul = data[data['REGION'] == 'Sul']

# Criar um painel com uma grade de 2 linhas por 3 colunas
fig, axes = plt.subplots(2, 3, figsize=(13, 7), sharex=True, sharey=True)

# Configurar cada subplot "axes[linha, coluna]"
# Posição (0, 0)
axes[0, 0].hist(norte['IDHM'], bins=20, color='#E86452', alpha=0.8)
axes[0, 0].set_title('Norte')
axes[0, 0].set_xlabel('IDHM')
axes[0, 0].set_ylabel('Número de municípios')

# Posição (0, 1)
axes[0, 1].hist(nordeste['IDHM'], bins=20, color='#F98C5C', alpha=0.8)
axes[0, 1].set_title('Nordeste')
axes[0, 1].set_xlabel('IDHM')

# Posição (0, 2)
axes[0, 2].hist(centro_oeste['IDHM'], bins=20, color='#9270CA', alpha=0.8)
axes[0, 2].set_title('Centro-Oeste')
axes[0, 2].set_xlabel('IDHM')

# Posição (1, 0)
axes[1, 0].hist(sudeste['IDHM'], bins=20, color='#5B8FF9', alpha=0.8)
axes[1, 0].set_title('Sudeste')
axes[1, 0].set_xlabel('IDHM')
axes[1, 0].set_ylabel('Número de municípios')

# Posição (1, 1)
axes[1, 1].hist(sul['IDHM'], bins=20, color='#5AD8A6', alpha=0.8)
axes[1, 1].set_title('Sul')
axes[1, 1].set_xlabel('IDHM')

# Remover a posição (1, 2) que ficou sem gráfico
fig.delaxes(axes[1, 2])

# Título geral do painel
fig.suptitle('Distribuição do IDHM por região do Brasil (2018)',
             fontweight='bold', fontsize=14)

plt.tight_layout()
plt.show()

### Boxplot

In [ ]:
# Carregamento do dataset
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Mapeamento das regiões
mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}
df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Remover municípios sem valor de IDHM
data = df_brasil.dropna(subset=['IDHM'])

# Ordena as regiões e monta uma lista de séries de IDHM, uma por região
regioes = sorted(data['REGION'].unique())
# Separa os valores de IDHM correspondentes em uma lista própria por região
grupos = [data[data['REGION'] == reg]['IDHM'] for reg in regioes]

# Criar a figura e desenha o boxplot
fig, ax = plt.subplots(figsize=(9, 6))

ax.boxplot(grupos, labels=regioes)

# Customizar
ax.set_xlabel('Região')
ax.set_ylabel('IDHM')
ax.set_title('Distribuição do IDHM por região do Brasil (2018)',
             fontweight='bold', fontsize=14)

plt.tight_layout()
plt.show()

In [ ]:
# Remove municípios sem valor de IDHM
data = df_brasil.dropna(subset=['IDHM'])

# Lista os estados em ordem alfabética e separa o IDHM de cada um em um grupo próprio
estados = sorted(data['STATE'].unique())
grupos = [data[data['STATE'] == uf]['IDHM'] for uf in estados]

fig, ax = plt.subplots(figsize=(14, 6))

# patch_artist=True habilita o preenchimento colorido das caixas
ax.boxplot(grupos, labels=estados, patch_artist=True,
           boxprops=dict(facecolor='#A9CCE3'))

ax.set_xlabel('Estado')
ax.set_ylabel('IDHM')
ax.set_title('Distribuição do IDHM por estado do Brasil (2018)',
             fontweight='bold', fontsize=14)

plt.tight_layout()
plt.show()

### Gráfico de Violino

In [ ]:
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

mapa_regioes = {
    'AC': 'Norte', 'AM': 'Norte', 'AP': 'Norte', 'PA': 'Norte', 'RO': 'Norte',
    'RR': 'Norte', 'TO': 'Norte', 'AL': 'Nordeste', 'BA': 'Nordeste',
    'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste',
    'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste', 'DF': 'Centro-Oeste',
    'GO': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MT': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}
df_brasil['REGION'] = df_brasil['STATE'].map(mapa_regioes)

# Remove municípios sem valor de IDHM
data = df_brasil.dropna(subset=['IDHM'])

# Lista as regiões em ordem alfabética, para definir a ordem dos violinos no eixo X
regioes = sorted(data['REGION'].unique())

fig, ax = plt.subplots(figsize=(9, 6))

sns.violinplot(data=data, x='REGION', y='IDHM', order=regioes, ax=ax, color='#5AD8A6')

ax.set_xlabel('Região')
ax.set_ylabel('IDHM')
ax.set_title('Distribuição do IDHM por região do Brasil (2018)',
             fontweight='bold')

plt.tight_layout()
plt.show()

In [ ]:
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

data = df_brasil.dropna(subset=['CAPITAL', 'IDHM']).copy()

# Criação do painel de subplots (1 linha, 2 colunas)
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(12, 5))

# Gráfico de Violino
violin_hdi = sns.violinplot(
    x='CAPITAL', y='IDHM', data=data,
    palette='Set3', ax=axes[0]
)
violin_hdi.set_xlabel('É Capital?', fontsize=12)
violin_hdi.set_ylabel('IDH', fontsize=12)
violin_hdi.set_title(label='Capital vs IDH', fontsize=15)

# Gráfico de Caixa
box_hdi = sns.boxplot(
    x='CAPITAL', y='IDHM', data=data,
    palette='Set3', ax=axes[1]
)
box_hdi.set_xlabel('É Capital?', fontsize=12)
box_hdi.set_ylabel('IDH', fontsize=12)
box_hdi.set_title(label='Capital vs IDH', fontsize=15)

plt.tight_layout()
plt.show()

### Nuvem de Palavras

In [ ]:
from wordcloud import WordCloud

df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

# Concatenação de todos os nomes de cidades em um único texto
text = ' '.join(df_brasil['CITY'])

# Remoção de palavras repetidas e irrelevantes (stop words)
stop_words = ['De', 'Do', 'Da']

# Mapeamento da frequência de cada palavra e produção da nuvem de palavras
wordcloud = WordCloud(
    background_color="white",   # cor de fundo da nuvem de palavras
    max_words=len(df_brasil),   # número máximo de palavras exibidas
    max_font_size=70,           # tamanho máximo da palavra mais frequente
    stopwords=stop_words,       # lista de palavras a ignorar
    collocations=False,         # conta apenas palavras isoladas, sem pares
    height=300,                 # altura da imagem gerada
    width=600                   # largura da imagem gerada
).generate(text)                # processa a string 'text' e conta a frequência de cada palavra, gerando a nuvem

plt.figure(figsize=(20, 12))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

### Mapa de Calor

In [ ]:
df_brasil = pd.read_csv('BRAZIL_CITIES.csv', sep=';')

variaveis = ['IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao',
             'ESTIMATED_POP', 'GDP']
data = df_brasil[variaveis].dropna()

# Calcula a matriz de correlação entre as variáveis
matriz_corr = data.corr()

# Gerar Mapa de Calor
sns.heatmap(
    matriz_corr,
    annot=True,       # exibe o valor numérico de cada correlação dentro da célula correspondente
    fmt='.2f',        # formata esse número com 2 casas decimais
    cmap='coolwarm',  # paleta de cores
    vmin=-1,          # menor valor possível da escala de cores
    vmax=1,           # maior valor possível da escala de cores
    center=0,         # centraliza a paleta de cores no valor 0
    ax=ax             # desenha o heatmap dentro dos eixos 'ax'
)

ax.set_title('Matriz de correlação entre variáveis socioeconômicas')

plt.tight_layout()
plt.show()

# **Aula 05 (06/11):**