[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SEU-USUARIO/NOME-DO-REPOSITORIO/blob/main/aula01.ipynb)

# **Análise e Visualização de dados**
*Prof. Jonathan Gil Müller - jgmuller@furb.br*



*   Função de imprimir
*   Variáveis
* Operadores matemáticos
* Arredondamento
* Interação com o Python
* Listas
* Dicionários e Dataframes
* Bibliotecas
* Carregar dados externos

# **Aula 01 (09/10): Introdução ao uso da linguagem Python**

## Imprimir, variáveis, arredondamento

In [ ]:
# A função print é utilizada para imprimir alguma informação na tela
print('Bom dia!')

Bom dia!

In [ ]:
print(2+3)

5

In [ ]:
# Variáveis
ValorInteiro = 5         # int
b            = 2.4 * 8   # float
texto        = "Olá"     # texto

# Imprimir na tela
print(f"{texto}. O valor da variável b é: {b}")

Olá. O valor da variável b é: 19.2

In [ ]:
# 1. Coleta de Dados
nome = 'Jonathan'
disc = 'AVD'
n1 = 7.5
n2 = 5.2
n3 = 2.5

# 2. Processamento dos Dados
media = round((n1 + n2 + n3) / 3, 1)

# 3. Imprimir os resultados
print(f'A média final do {nome} em {disc} é {media}')

A média final do Jonathan em AVD é 5.1

## Interação com Python - input

In [ ]:
# Interagindo para fornecer os dados
nota1 = float(input('Qual a sua Nota 1?'))
nota2 = float(input('Qual a sua Nota 2?'))
nota3 = float(input('Qual a sua Nota 3?'))

media = (nota1 + nota2 + nota3) / 3

print(media)

Qual a sua Nota 1?6
Qual a sua Nota 2?7
Qual a sua Nota 3?8
7.0

In [ ]:
# Imprimindo o tipo de objeto da variável
print(type(nota1))

<class 'float'>

## Listas

In [ ]:
# usar [ ] para definir uma lista
lista_notas = [6.0, 7.0, 8.0]

# A função 'sum' soma todos os valores da lista
# A função 'len' retorna o total de elementos da lista
media = sum(lista_notas) / len(lista_notas)

print(media)

7.0

In [ ]:
print(type(lista_notas))

<class 'list'>

## Dicionários, dataframes e bibliotecas

In [ ]:
# Usar { } para definir um dicionário
# {'nome 01': valor 01, 'nome 02': valor 02, ...}
dicionario = {
    'nomes':['nomeA', 'nomeB', 'nomeC'],
    'nota1':[5.0, 7.0, 8.0],
    'nota2':[5.0, 5.6, 9.8],
    'nota3':[7.0, 4.6, 7.8]
}

print(dicionario)

{'nomes': ['nomeA', 'nomeB', 'nomeC'], 'nota1': [5.0, 7.0, 8.0], 'nota2': [5.0, 5.6, 9.8], 'nota3': [7.0, 4.6, 7.8]}

In [ ]:
# Uma biblioteca é como uma 'caixa de ferramentas' com várias funções já programadas
# 'pandas' é o nome da biblioteca e 'pd' é o apelido.
# Pandas é uma biblioteca com funções para manipulação de tabelas
import pandas as pd

df = pd.DataFrame(dicionario)

df.head()

   nomes  nota1  nota2  nota3
0  nomeA    5.0    5.0    7.0
1  nomeB    7.0    5.6    4.6
2  nomeC    8.0    9.8    7.8

In [ ]:
# Numpy é uma biblioteca para cálculos matemáticos
import numpy as np

media_n1 = np.mean(df['nota1'])

print(media_n1)

6.666666666666667

In [ ]:
# Criar uma nova coluna com a média dos alunos

df['Média'] = ((df['nota1'] + df['nota2'] + df['nota3']) / 3).round(1)

df.head()

   nomes  nota1  nota2  nota3  Média
0  nomeA    5.0    5.0    7.0    5.7
1  nomeB    7.0    5.6    4.6    5.7
2  nomeC    8.0    9.8    7.8    8.5

## Importar uma tabela externa de dados para o ambiente Colab

In [ ]:
dados = pd.read_excel('[Estatistica-BCD]_DadosQuestionario_20262.xlsx')

dados.describe()

,ID,Você já morou em quantas cidades?,Como você avalia seu conhecimento em Matemática?,Data de nascimento:,Como você avalia seu cuidado com sua alimentação?,Quantos livros você leu no último ano?,Quantos idiomas você sabe?
count,80.0000,80.000000,80.000000,80,80.000000,80.000000,80.000000
mean,40.5000,1.725000,6.662500,2004-08-13 08:06:00,6.225000,3.462500,1.987500
min,1.0000,0.000000,2.000000,1975-03-18 00:00:00,0.000000,0.000000,0.000000
25%,20.7500,1.000000,6.000000,2003-02-24 18:00:00,5.000000,1.000000,1.000000
50%,40.5000,1.000000,7.000000,2006-07-02 12:00:00,6.500000,2.000000,2.000000
75%,60.2500,2.000000,8.000000,2007-12-01 06:00:00,8.000000,4.000000,2.000000
max,80.0000,9.000000,10.000000,2026-12-16 00:00:00,10.000000,35.000000,15.000000
std,23.2379,1.475324,1.492121,NaN,2.210304,5.641043,1.641964

In [ ]:
media = np.mean(dados['Como você avalia seu conhecimento em Matemática?'])

print(media)

6.6625

In [ ]:
# EXERCÍCIO

#Dados
venda = 1.7
margem = 35

#Processamento
custo = (venda * 100) / (100 + margem)

#Resultado
print(custo)

1.2592592592592593

# **Aula 02 (16/10): Organização, estruturação, tratamento e qualidade de dados**